routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers;

Route::redirect('/', '/dashboard/recipes');

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::prefix('dashboard')
        ->name('dashboard.')
        ->group(function () {
            Route::get('/', [Controllers\DashboardController::class, "index"])->name('index');
            Route::get('/recipes', [Controllers\DashboardController::class, 'recipes'])->name('recipes');
            Route::get('/measures', [Controllers\DashboardController::class, 'measures'])->name('measures');
            Route::get('/ingredients', [Controllers\DashboardController::class, 'ingredients'])->name('ingredients');
            Route::prefix('recipe')
                ->name('recipe.')
                ->group(function () {
                    Route::get('/create', [Controllers\RecipeController::class, 'create'])->name('create');
                    Route::put('/instantiate', [Controllers\RecipeController::class, 'instantiate'])->name('instantiate');
                    Route::delete('/{recipe}/destroy', [Controllers\RecipeController::class, 'destroy'])->name('destroy');
                    Route::post('/update', [Controllers\RecipeController::class, 'update'])->name('update');
                    Route::get('/{recipe}', [Controllers\RecipeController::class, 'show'])->name('index');
                    Route::get('/{recipe}/view', [Controllers\RecipeController::class, 'show'])->name('show');
                    Route::get('/{recipe}/edit', [Controllers\RecipeController::class, 'edit'])->name('edit');
                });
            Route::prefix('measure')
                ->name('measure.')
                ->group(function () {
                    Route::post('/store', [Controllers\MeasureController::class, 'store'])->name('store');
                    Route::delete('/remove/{measure}', [Controllers\MeasureController::class, 'remove'])->name('remove');
                });
            Route::prefix('ingredient')
                ->name('ingredient.')
                ->group(function () {
                    Route::get('/edit/{ingredient}', [Controllers\IngredientController::class, 'edit'])->name('edit');
                    Route::get('/create', [Controllers\IngredientController::class, 'create'])->name('create');
                    Route::post('/store', [Controllers\IngredientController::class, 'store'])->name('store');
                    Route::delete('/remove/{ingredient}', [Controllers\IngredientController::class, 'remove'])->name('remove');
                    Route::post('/update/{ingredient}', [Controllers\IngredientController::class, 'update'])->name('update');
                });
            Route::resource('/categories', 'CategoryController');
        });
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasManyThrough;
use Illuminate\Database\Eloquent\Relations\HasOne;

/**
 * App\Category
 *
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Category[] $children
 * @property-read \App\Category $parent
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category query()
 * @mixin \Eloquent
 */
class Category extends Model
{
    protected $table = 'category';

    protected $fillable = [
        "name",
        "parent_id"
    ];

    public function parent(): HasOne
    {
        return $this->hasOne(Category::class, "id", "parent_id");
    }

    public function children(): HasMany
    {
        return $this->hasMany(Category::class, "parent_id", "id");
    }

    public function recipes(): HasManyThrough
    {
        return $this->hasManyThrough(Recipe::class, RecipeCategory::class, "category_id", "id", "id", "recipe_id");
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\StoreCategory;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index(int $count = 10)
    {
        return view('dashboard.categories', [
            'categories' => Category::with('parent')->paginate($count)
        ]);
    }

    public function create()
    {
        return view('dashboard.category.create', [
            'categories' => Category::all()
        ]);
    }

    public function store(StoreCategory $request)
    {
        Category::create([
            'name' => $request->get('name'),
            'parent_id' => ($id = $request->get('parent_id')) ? $id : null
        ]);

        return redirect(route('dashboard.categories.index'));
    }

    public function destroy(Category $category)
    {
        $errors = [];

        if ($category->children()->count() > 0) {
            $errors['children'] = 'Категория содержит подкатегории';
        }

        if ($category->recipes()->count() > 0) {
            $errors['recipes'] = 'Категорию используют в некоторых рецептах';
        }

        if (empty($errors)) {
            $category->delete();
        }

        return redirect()
            ->back()
            ->withErrors($errors);
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Ingredient;
use App\Measure;
use App\Recipe;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('dashboard.index');
    }

    public function recipes(int $count = 10)
    {
        return view('dashboard.recipes', [
            'recipes' => Recipe::with('categories')->paginate($count)
        ]);
    }

    public function ingredients()
    {
        return view('dashboard.ingredients', [
            'ingredients' => Ingredient::with('measure')->get()->all()
        ]);
    }

    public function measures(int $count = 10)
    {
        return view('dashboard.measures', [
            'measures' => Measure::query()->paginate($count)
        ]);
    }
}

resources/views/dashboard/category/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="container m-2">
        <h2 class="m-1">Добавление категории</h2>
        <form method="POST" action="{{ route('dashboard.categories.store') }}">
            @csrf

            <div class="container-fluid border-bottom">
                <div class="form-group row">
                    <label for="name" class="col-form-label text-md-right">Название</label>
                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                               name="name"
                               value="{{ old('name') }}" required autocomplete="category" autofocus>

                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <label for="parent_id" class="col-form-label text-md-right">Родительская категория</label>
                    <div class="col-md-6">
                        <select id="parent_id" type="text" class="form-control @error('parent_id') is-invalid @enderror"
                                name="parent_id">
                            @foreach($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>

                        @error('parent_id')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div>
            </div>
            <div class="container-fluid d-flex justify-content-end">
                <button type="submit" class="btn btn-outline-success m-2">Сохранить</button>
            </div>
        </form>
    </div>
@endsection