routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers;

Route::redirect('/', '/dashboard/recipes');

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::prefix('dashboard')
        ->name('dashboard.')
        ->group(function () {
            Route::get('/', [Controllers\DashboardController::class, "index"])->name('index');
            Route::get('/recipes', [Controllers\DashboardController::class, 'recipes'])->name('recipes');
            Route::get('/measures', [Controllers\DashboardController::class, 'measures'])->name('measures');
            Route::get('/ingredients', [Controllers\DashboardController::class, 'ingredients'])->name('ingredients');
            Route::prefix('recipe')
                ->name('recipe.')
                ->group(function () {
                    Route::get('/create', [Controllers\RecipeController::class, 'create'])->name('create');
                    Route::put('/instantiate', [Controllers\RecipeController::class, 'instantiate'])->name('instantiate');
                    Route::delete('/{recipe}/destroy', [Controllers\RecipeController::class, 'destroy'])->name('destroy');
                    Route::post('/update', [Controllers\RecipeController::class, 'update'])->name('update');
                    Route::get('/{recipe}', [Controllers\RecipeController::class, 'show'])->name('index');
                    Route::get('/{recipe}/view', [Controllers\RecipeController::class, 'show'])->name('show');
                    Route::get('/{recipe}/edit', [Controllers\RecipeController::class, 'edit'])->name('edit');
                });
            Route::prefix('measure')
                ->name('measure.')
                ->group(function () {
                    Route::post('/store', [Controllers\MeasureController::class, 'store'])->name('store');
                    Route::delete('/remove/{measure}', [Controllers\MeasureController::class, 'remove'])->name('remove');
                });
            Route::prefix('ingredient')
                ->name('ingredient.')
                ->group(function () {
                    Route::get('/edit/{ingredient}', [Controllers\IngredientController::class, 'edit'])->name('edit');
                    Route::get('/create', [Controllers\IngredientController::class, 'create'])->name('create');
                    Route::post('/store', [Controllers\IngredientController::class, 'store'])->name('store');
                    Route::delete('/remove/{ingredient}', [Controllers\IngredientController::class, 'remove'])->name('remove');
                    Route::post('/update/{ingredient}', [Controllers\IngredientController::class, 'update'])->name('update');
                });
            Route::resource('/categories', 'CategoryController');
        });
});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Ingredient;
use App\Measure;
use App\Recipe;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('dashboard.index');
    }

    public function recipes(int $count = 10)
    {
        return view('dashboard.recipes', [
            'recipes' => Recipe::with('categories')->paginate($count)
        ]);
    }

    public function ingredients()
    {
        return view('dashboard.ingredients', [
            'ingredients' => Ingredient::with('measure')->get()->all()
        ]);
    }

    public function measures(int $count = 10)
    {
        return view('dashboard.measures', [
            'measures' => Measure::query()->paginate($count)
        ]);
    }
}

resources/views/dashboard/categories.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="container-fluid justify-content-between d-flex">
        <h3 class="m-1">Категории</h3>
        <a href="{{ route('dashboard.categories.create') }}" role="button"
           class="btn btn-sm btn-primary rounded-0 p-1 m-1">
            Добавить категорию
        </a>
    </div>
    @error('recipes')
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ $message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    @enderror

    @error('children')
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ $message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    @enderror
    <div class="container-fluid">
        <table class="table table-sm">
            <thead>
            <tr>
                <th>#</th>
                <th>Название</th>
                <th>Родительская категория</th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody style="height: 100px; overflow-y: scroll">
            @foreach($categories as $category)
                <tr>
                    <td>{{ $category->id }}</td>
                    <td>{{ $category->name }}</td>
                    <td>{{ $category->parent->name ?? '' }}</td>
                    <td>
                        <form method="POST" action="{{ route('dashboard.categories.destroy', $category->id) }}">
                            @csrf
                            @method('DELETE')

                            <button class="btn btn-sm btn-outline-danger" type="submit">
                                <i class="fas fa-times"></i>
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $categories->links('vendor.pagination.bootstrap-4') }}
    </div>
@endsection

resources/views/dashboard/ingredients.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="container-fluid justify-content-between d-flex">
        <h3 class="m-1">Мои ингредиенты</h3>
        <a href="{{ route('dashboard.ingredient.create') }}" role="button" class="btn btn-sm btn-primary rounded-0 p-1 m-1">
            Добавить ингредиент
        </a>
    </div>
    <table class="table table-sm">
        <thead>
        <tr>
            <th>#</th>
            <th>Название</th>
            <th>Мерность</th>
            <th>Действия</th>
        </tr>
        </thead>
        <tbody>
        @foreach($ingredients as $ingredient)
            <tr>
                <td>{{ $ingredient->id }}</td>
                <td>{{ $ingredient->name }}</td>
                <td>{{ $ingredient->measure->name }} ({{ $ingredient->measure->postfix }})</td>
                <td>
                    <div class="container-fluid row">
                        <form method="POST"
                              action="{{ route('dashboard.ingredient.remove', $ingredient->id) }}">
                            @csrf
                            @method('DELETE')

                            <button class="btn btn-sm btn-outline-danger m-1">
                                <i class="fas fa-times"></i>
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection

resources/views/dashboard/measures.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="container-fluid">
        <h3 class="m-1">Мои мерности</h3>
    </div>
    <div class="row">
        <div class="col-6">
            <table class="table table-sm">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Название</th>
                    <th>Постфикс</th>
                    <th>Действия</th>
                </tr>
                </thead>
                <tbody>
                @foreach($measures as $measure)
                    <tr>
                        <td>{{ $measure->id }}</td>
                        <td>{{ $measure->name }}</td>
                        <td>{{ $measure->postfix }}</td>
                        <td>
                            <form method="POST" action="{{ route('dashboard.measure.remove', $measure->id) }}">
                                @csrf
                                @method('DELETE')

                                <button class="btn btn-sm btn-outline-danger" type="submit">
                                    <i class="fas fa-times"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div>
            <form method="POST" action="{{ route('dashboard.measure.store') }}">
                @csrf

                <div class="form-group">
                    <label for="name">Название</label>
                    <input id="name" name="name" type="text" class="form-control">
                    <label for="postfix">Постфикс</label>
                    <input id="postfix" name="postfix" type="text" class="form-control">

                </div>
                <div class="form-group">
                    <button class="btn btn-outline-success" type="submit">Добавить</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/dashboard/recipes.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="container-fluid justify-content-between d-flex">
        <h3 class="m-1">Мои рецепты</h3>
        <a href="{{ route('dashboard.recipe.create') }}" role="button" class="btn btn-sm btn-primary rounded-0 p-1 m-1">
            Добавить рецепт
        </a>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th>#</th>
            <th>Имя</th>
            <th>Описание</th>
            <th>Категории</th>
            <th>Действия</th>
        </tr>
        </thead>
        <tbody>
        @foreach($recipes as $recipe)
            <tr>
                <td>{{ $recipe->id }}</td>
                <td>{{ $recipe->name }}</td>
                <td>{{ $recipe->description }}</td>
                <td>
                    @foreach($recipe->categories as $category)
                        <span class="text-info">{{ $category->name }}</span><br>
                    @endforeach
                </td>
                <td class="row">
                    <a href="{{ route('dashboard.recipe.show', ['recipe' => $recipe->id]) }}"
                       role="button"
                       class="btn btn-sm btn-outline-secondary rounded-0 m-1">
                        <i class="far fa-eye"></i>
                    </a>
                    <form method="POST" action="{{ route('dashboard.recipe.destroy', $recipe->id) }}">
                        @csrf
                        @method('DELETE')
                        <button type="submit"
                                class="btn btn-sm btn-outline-danger rounded-0 m-1">
                            <i class="fa fa-times"></i>
                        </button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $recipes->links('vendor.pagination.bootstrap-4') }}
@endsection