routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers;

Route::redirect('/', '/dashboard/recipes');

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::prefix('dashboard')
        ->name('dashboard.')
        ->group(function () {
            Route::get('/', [Controllers\DashboardController::class, "index"])->name('index');
            Route::get('/recipes', [Controllers\DashboardController::class, 'recipes'])->name('recipes');
            Route::get('/measures', [Controllers\DashboardController::class, 'measures'])->name('measures');
            Route::get('/ingredients', [Controllers\DashboardController::class, 'ingredients'])->name('ingredients');
            Route::prefix('recipe')
                ->name('recipe.')
                ->group(function () {
                    Route::get('/create', [Controllers\RecipeController::class, 'create'])->name('create');
                    Route::put('/instantiate', [Controllers\RecipeController::class, 'instantiate'])->name('instantiate');
                    Route::delete('/{recipe}/destroy', [Controllers\RecipeController::class, 'destroy'])->name('destroy');
                    Route::post('/update', [Controllers\RecipeController::class, 'update'])->name('update');
                    Route::get('/{recipe}', [Controllers\RecipeController::class, 'show'])->name('index');
                    Route::get('/{recipe}/view', [Controllers\RecipeController::class, 'show'])->name('show');
                    Route::get('/{recipe}/edit', [Controllers\RecipeController::class, 'edit'])->name('edit');
                });
            Route::prefix('measure')
                ->name('measure.')
                ->group(function () {
                    Route::post('/store', [Controllers\MeasureController::class, 'store'])->name('store');
                    Route::delete('/remove/{measure}', [Controllers\MeasureController::class, 'remove'])->name('remove');
                });
            Route::prefix('ingredient')
                ->name('ingredient.')
                ->group(function () {
                    Route::get('/edit/{ingredient}', [Controllers\IngredientController::class, 'edit'])->name('edit');
                    Route::get('/create', [Controllers\IngredientController::class, 'create'])->name('create');
                    Route::post('/store', [Controllers\IngredientController::class, 'store'])->name('store');
                    Route::delete('/remove/{ingredient}', [Controllers\IngredientController::class, 'remove'])->name('remove');
                    Route::post('/update/{ingredient}', [Controllers\IngredientController::class, 'update'])->name('update');
                });
            Route::resource('/categories', 'CategoryController');
        });
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/all.js') }}" defer></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/main.css') }}" rel="stylesheet">
    <link href="{{ asset('css/all.css') }}" rel="stylesheet">

    @stack('scripts')
</head>
<body>
    <div id="app" class="h-100">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url('/') }}">
                    <i class="fas fa-utensils"></i>
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    <i class="far fa-user"></i>
                                    {{ Auth::user()->name }}
                                    <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        <main id="content-wrapper">
            @yield('content-wrapper')
        </main>
    </div>
</body>
</html>

resources/views/layouts/dashboard.blade.php
@extends("layouts.app")

@section('content-wrapper')
    <div class="container-fluid h-100">
        <div class="row h-100">
            <div id="sidebar" class="col-2 border-right h-100 shadow-sm">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{{ route('dashboard.recipes') }}">
                            <i class="fas fa-book"></i>
                            <span>Мои рецепты</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{{ route("dashboard.ingredients") }}">
                            <i class="fas fa-puzzle-piece"></i>
                            <span>Ингредиенты</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{{ route('dashboard.measures') }}">
                            <i class="fas fa-weight-hanging"></i>
                            <span>Мерности</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{{ route('dashboard.categories.index') }}">
                            <i class="fas fa-align-justify"></i>
                            <span>Категории</span>
                        </a>
                    </li>
                </ul>
                <div class="nav-item">
                </div>
            </div>
            <div id="content" class="col-10 h-100 fixed-overflow">
                @if(Session::has('success'))
                    <div class="alert alert-success alert-dismissible fade show m-1 p-1 rounded-0" role="alert">
                        {{ Session::get('success') }}
                        <button type="button" class="close p-1" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif

                @error('warning')
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ $message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @enderror

                @yield('content')
            </div>
        </div>
    </div>
@endsection