routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers;

Route::redirect('/', '/dashboard/recipes');

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::prefix('dashboard')
        ->name('dashboard.')
        ->group(function () {
            Route::get('/', [Controllers\DashboardController::class, "index"])->name('index');
            Route::get('/recipes', [Controllers\DashboardController::class, 'recipes'])->name('recipes');
            Route::get('/measures', [Controllers\DashboardController::class, 'measures'])->name('measures');
            Route::get('/ingredients', [Controllers\DashboardController::class, 'ingredients'])->name('ingredients');
            Route::prefix('recipe')
                ->name('recipe.')
                ->group(function () {
                    Route::get('/create', [Controllers\RecipeController::class, 'create'])->name('create');
                    Route::put('/instantiate', [Controllers\RecipeController::class, 'instantiate'])->name('instantiate');
                    Route::delete('/{recipe}/destroy', [Controllers\RecipeController::class, 'destroy'])->name('destroy');
                    Route::post('/update', [Controllers\RecipeController::class, 'update'])->name('update');
                    Route::get('/{recipe}', [Controllers\RecipeController::class, 'show'])->name('index');
                    Route::get('/{recipe}/view', [Controllers\RecipeController::class, 'show'])->name('show');
                    Route::get('/{recipe}/edit', [Controllers\RecipeController::class, 'edit'])->name('edit');
                });
            Route::prefix('measure')
                ->name('measure.')
                ->group(function () {
                    Route::post('/store', [Controllers\MeasureController::class, 'store'])->name('store');
                    Route::delete('/remove/{measure}', [Controllers\MeasureController::class, 'remove'])->name('remove');
                });
            Route::prefix('ingredient')
                ->name('ingredient.')
                ->group(function () {
                    Route::get('/edit/{ingredient}', [Controllers\IngredientController::class, 'edit'])->name('edit');
                    Route::get('/create', [Controllers\IngredientController::class, 'create'])->name('create');
                    Route::post('/store', [Controllers\IngredientController::class, 'store'])->name('store');
                    Route::delete('/remove/{ingredient}', [Controllers\IngredientController::class, 'remove'])->name('remove');
                    Route::post('/update/{ingredient}', [Controllers\IngredientController::class, 'update'])->name('update');
                });
            Route::resource('/categories', 'CategoryController');
        });
});

app/Recipe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasManyThrough;
use Illuminate\Database\Eloquent\Relations\HasOne;

/**
 * App\Recipe
 *
 * @property-read \App\User $author
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Category[] $categories
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\RecipeComposition[] $compositions
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Recipe newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Recipe newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Recipe query()
 * @mixin \Eloquent
 */
class Recipe extends Model
{
    protected $table = 'recipe';

    protected $fillable = [
        "name",
        "description",
        "author_id",
    ];

    public function author(): HasOne
    {
        return $this->hasOne(User::class, "author_id", "id");
    }

    public function ingredients()
    {
        return $this->hasMany(RecipeComposition::class, 'recipe_id', 'id')->with('ingredient');
    }

    public function categories(): HasManyThrough
    {
        return $this->hasManyThrough(Category::class, RecipeCategory::class, "recipe_id", "id", "id", "category_id");
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Ingredient;
use App\Measure;
use App\Recipe;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('dashboard.index');
    }

    public function recipes(int $count = 10)
    {
        return view('dashboard.recipes', [
            'recipes' => Recipe::with('categories')->paginate($count)
        ]);
    }

    public function ingredients()
    {
        return view('dashboard.ingredients', [
            'ingredients' => Ingredient::with('measure')->get()->all()
        ]);
    }

    public function measures(int $count = 10)
    {
        return view('dashboard.measures', [
            'measures' => Measure::query()->paginate($count)
        ]);
    }
}

app/Http/Controllers/RecipeController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Ingredient;
use App\Measure;
use App\Recipe;
use App\RecipeCategory;
use App\RecipeComposition;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class RecipeController extends Controller
{
    public function show(Recipe $recipe)
    {
        return view('dashboard.recipe.view', [
            'recipe' => $recipe,
        ]);
    }

    public function create()
    {
        return view('dashboard.recipe.create', [
            'measures' => Measure::all(),
            'ingredients' => Ingredient::with('measure')->get()->all(),
            'categories' => Category::all(),
        ]);
    }

    public function update(Request $request)
    {
        if ($request->has('ingredient')) {
            foreach ($request->get('ingredient') as $ingredient) {
                RecipeComposition::query()
                    ->where([
                        'recipe_id' => $request->get('recipe_id'),
                        'ingredient_id' => $ingredient['id']
                    ])
                    ->update([
                        'count' => $ingredient['count']
                    ]);
            }
        }

        return redirect()->back()->with('success', 'Рецепт успешно обновлен');
    }

    public function instantiate(Request $request)
    {
        $name = $request->get('name');
        $description = $request->get('description');
        $categories = $request->get('category_id') ?? [];
        $ingredients = $request->get('ingredient');
        $validator = Validator::make(
            [
                'name' => $name,
                'description' => $description,
                'categories' => $categories,
                'ingredients' => $ingredients,
            ],
            [
                'name' => 'unique:recipe',
                'description' => 'min:5',
                'categories' => 'exists:category,id',
                'ingredients.ingredient_id' => 'exists:ingredient,id',
                'ingredient.count' => 'min:1'
            ]
        );

        if ($validator->fails()) {
            return redirect()
                ->back()
                ->withErrors($validator)
                ->withInput($request->all());
        }

        $recipe = Recipe::create([
            'name' => $name,
            'description' => $description,
            'author_id' => $request->user()->id,
        ]);

        foreach ($ingredients as $ingredient) {
            RecipeComposition::create([
                'recipe_id' => $recipe->id,
                'ingredient_id' => $ingredient['ingredient_id'],
                'count' => $ingredient['count'],
            ]);
        }

        foreach ($categories as $category) {
            RecipeCategory::create([
                'recipe_id' => $recipe->id,
                'category_id' => $category
            ]);
        }

        return redirect()
            ->to(route('dashboard.recipes'))
            ->with('success', 'Рецепт успешно сохранен!');
    }

    public function destroy(Recipe $recipe)
    {
        RecipeCategory::query()
            ->where(['recipe_id' => $recipe->id])
            ->delete();

        RecipeComposition::query()
            ->where(['recipe_id' => $recipe->id])
            ->delete();

        $recipe->delete();

        return redirect()->back()->with('success', 'Рецепт успешно удален');
    }
}

resources/views/dashboard/recipe/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="container m-2">
        <h2 class="m-1">Добавление рецепта</h2>
        @error('ingredient')
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ $message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        @enderror
        <form method="POST" action="{{ route('dashboard.recipe.instantiate') }}">
            @csrf
            @method('PUT')

            <div class="container border-bottom">
                <div class="form-group row">
                    <label for="recipe-name" class=" col-form-label text-md-right">Название</label>
                    <div class="col-md-6">
                        <input id="recipe-name" type="text"
                               class="form-control @error('recipe-name') is-invalid @enderror"
                               name="name"
                               value="{{ old('recipe-name') }}" required autofocus>
                        @error('recipe-name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <label for="description" class="col-form-label text-md-right">Описание</label>
                    <div class="col-md-6">
                    <textarea rows="3" id="description" type="text"
                              class="form-control @error('description') is-invalid @enderror"
                              name="description">
                        {{ old('description') }}
                    </textarea>
                        @error('description')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div>
            </div>

            <h2 class="m-1">Категории</h2>
            <div class="container border-bottom">
                <div id="recipe-categories" class="container-fluid row">
                </div>
                <div class="container-fluid d-flex justify-content-between">
                    <button id="append-category" class="btn btn-sm btn-dark m-2 rounded-0" type="button">
                        добавить
                    </button>
                </div>
            </div>

            <h2 class="m-1">Ингредиенты</h2>
            <div class="container border-bottom">
                <div id="recipe-ingredients">
                </div>
                <div class="container-fluid d-flex justify-content-between">
                    <button id="append-ingredient" class="btn btn-sm btn-dark m-2 rounded-0" type="button">
                        добавить
                    </button>
                    <div>
                        <span class="text-info">Нет в списке?</span>
                        <button data-toggle="modal" data-target="#ingredientCreatorModal" id="create-ingredient"
                                type="button"
                                class="btn btn-sm btn-outline-secondary m-2 rounded-0">Создать новый ингредиент
                        </button>
                    </div>
                </div>
            </div>

            <div class="container d-flex justify-content-end">
                <button class="btn btn-outline-success col-2 m-2 rounded-0" type="submit">Сохранить</button>
            </div>
        </form>
    </div>
    <script>
        $(document).ready(function () {
            let ingredients = @json($ingredients);
            let categories = @json($categories);
            let count = 0;

            $("#append-ingredient").on('click', function () {
                let ingredient = $("<div></div>");
                let select = $(`<select name="ingredient[${count}][ingredient_id]" class="form-control col m-1"></select>`);

                ingredient.attr("class", "form-group row");
                Array.from(ingredients).forEach(function (item) {
                    select.append($(`<option value="${item.id}">${item.name} (${item.measure.postfix})</option>`))
                });
                ingredient.append(select);
                ingredient.append(
                    $(`<label for="$ingredient-${count}" class="col-form-label m-1">Количество:</label>`),
                    $(`<input id="ingredient-${count}" name="ingredient[${count}][count]" class="form-control col-1 m-1" type="number">`)
                );

                count = count + 1;
                $("#recipe-ingredients").append(ingredient);
            });

            $("#append-category").on('click', function () {
                let category = $('<div class="col"></div>');
                let select = $(`<select name="category_id[]" class="form-control-sm m-1"></select>`);

                Array.from(categories).forEach(function (item) {
                    select.append($(`<option value="${item.id}">${item.name}</option>`))
                });
                category.append(select);

                count = count + 1;
                $("#recipe-categories").append(category);
            });
        });
    </script>

    <div class="modal" id="ingredientCreatorModal" tabindex="-1" role="dialog">
        <form method="POST" action="{{ route('dashboard.ingredient.store') }}">
            @csrf

            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Добавление игредиента</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <label for="name">Ингредиент</label>
                        <input id="name" class="form-control" type="text" name="name">
                        <label for="measure_id">Мерность</label>

                        <div class="form-group">
                            <select id="measure_id" class="form-control" name="measure_id">
                                @foreach($measures as $measure)
                                    <option value="{{ $measure->id }}">
                                        {{ $measure->name }}, {{ $measure->postfix }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary" onclick="">Сохранить</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/dashboard/recipe/view.blade.php
@extends('layouts.dashboard')

@section('content')
    <form method="POST" action="{{ route('dashboard.recipe.update', ['recipe_id' => $recipe->id]) }}">
        @csrf
        <div class="container-fluid border-bottom">
            <h2>{{ $recipe->name }}</h2>
        </div>
        <div class="container-fluid border-bottom">
            <h3>Описание</h3>
            {{ $recipe->description }}
        </div>
        <div class="container-fluid border-bottom">
            <h3>Категории</h3>
            @foreach($recipe->categories as $category)
                <span class="text-info">{{ $category->name }}; </span>
            @endforeach
        </div>
        <div class="container-fluid border-bottom">
            <h3>Игредиенты</h3>
            @foreach($recipe->ingredients as $key => $composition)
                <div class="form-group row m-1">
                    <label class="col-form-label"
                           for="ingredient-{{ $composition->ingredient->id }}">{{ $composition->ingredient->name }}
                        ({{ $composition->ingredient->measure->postfix }})</label>
                    <input type="hidden" name="ingredient[{{ $key }}][id]" value="{{ $composition->ingredient->id }}">
                    <input id="ingredient-{{ $composition->ingredient->id }}" value="{{ $composition->count }}"
                           type="number" name="ingredient[{{ $key }}][count]"
                           class="form-control form-control-sm m-1 col-1">
                </div>
            @endforeach
        </div>
        <div class="form-group">
            <button class="btn btn-success" type="submit">Обновить</button>
        </div>
    </form>
@endsection